name: my_custom_widget
description: Showcase of custom widget 

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  cached_network_image:
#  flutter_form_builder: ^3.13.6

  get:

  image_cropper:
  image_picker:

  path_provider:
  permission_handler:

  shimmer:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

